version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      NODE_ENV: development
      DB_HOST: db
      MYSQL_DATABASE: ${MYSQL_DATABASE_DEV}
      MYSQL_USER: root
      MYSQL_PASSWORD: ${MYSQL_PASSWORD_DEV}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD_DEV}
      SESSION_SECRET: ${SESSION_SECRET}
      JWT_SECRET: ${JWT_SECRET}
    volumes:
      - ./backend:/app
      - /app/node_modules
    restart: always

  db:
    image: mysql:8.0
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE_DEV}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD_DEV}
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
